# Generated by Django 5.2 on 2025-04-25 16:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbidities',
            fields=[
                ('comorbidity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('birthday', models.DateTimeField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('hospital_registration', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialists',
            fields=[
                ('specialist_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialist_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('city_character', models.CharField(blank=True, max_length=255, null=True)),
                ('state_character', models.CharField(blank=True, max_length=2, null=True)),
                ('specialist_character', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='app_cicatrizando.patients')),
            ],
        ),
        migrations.AddField(
            model_name='patients',
            name='specialist_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='app_cicatrizando.specialists'),
        ),
        migrations.CreateModel(
            name='Wound',
            fields=[
                ('wound_id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cicatrizando.images')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wounds', to='app_cicatrizando.patients')),
                ('specialist_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wounds', to='app_cicatrizando.specialists')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingRecords',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('track_date', models.DateTimeField()),
                ('exudate_amount', models.CharField(max_length=50)),
                ('exudate_type', models.CharField(max_length=50)),
                ('tissue_type', models.CharField(max_length=50)),
                ('wound_edges', models.CharField(blank=True, max_length=100, null=True)),
                ('skin_around', models.CharField(blank=True, max_length=100, null=True)),
                ('had_a_fever', models.BooleanField(blank=True, null=True)),
                ('pain_level', models.CharField(blank=True, max_length=10, null=True)),
                ('image_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cicatrizando.images')),
                ('specialist_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_records', to='app_cicatrizando.specialists')),
                ('wound_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='app_cicatrizando.wound')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('smoke_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('comorbidities', models.ManyToManyField(related_name='observations', to='app_cicatrizando.comorbidities')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='app_cicatrizando.patients')),
                ('wound_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='app_cicatrizando.wound')),
            ],
        ),
    ]
