# Generated by Django 5.2 on 2025-06-13 02:40

import app_cicatrizando.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cicatrizando', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=app_cicatrizando.models.get_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='procedureoccurrence',
            name='procedure_occurrence_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PatientExtraNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_extra_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota Extra do Paciente',
                'verbose_name_plural': 'Notas Extras dos Pacientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingRecordImage',
            fields=[
                ('tracking_record_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_cicatrizando.image')),
                ('tracking_record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_cicatrizando.procedureoccurrence')),
            ],
        ),
        migrations.CreateModel(
            name='WoundImage',
            fields=[
                ('wound_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_cicatrizando.image')),
                ('wound', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_cicatrizando.conditionoccurrence')),
            ],
        ),
        migrations.DeleteModel(
            name='SpecialistNonOmopInfos',
        ),
    ]
