# Generated by Django 6.0.2 on 2026-05-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cicatrizando', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comorbidity',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
