# Generated by Django 5.2 on 2025-06-13 03:26

import app_cicatrizando.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cicatrizando", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(upload_to=app_cicatrizando.models.get_file_path),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="conditionoccurrence",
            name="condition_occurrence_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="procedureoccurrence",
            name="procedure_occurrence_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="TrackingRecordImage",
            fields=[
                (
                    "tracking_record_image_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_cicatrizando.image",
                    ),
                ),
                (
                    "tracking_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_cicatrizando.procedureoccurrence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WoundImage",
            fields=[
                ("wound_image_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_cicatrizando.image",
                    ),
                ),
                (
                    "wound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_cicatrizando.conditionoccurrence",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SpecialistNonOmopInfos",
        ),
    ]
