# Generated by Django 5.2 on 2025-05-15 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cicatrizando', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='comorbidities',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='wound_id',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='sex',
        ),
        migrations.AddField(
            model_name='patients',
            name='accept_tcl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patients',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patients',
            name='drink_frequency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='smoke_frequency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialists',
            name='speciality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackingrecords',
            name='dressing_changer_per_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trackingrecords',
            name='extra_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackingrecords',
            name='guidelines_to_patient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trackingrecords',
            name='pain_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PatientComorbidities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbidity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='app_cicatrizando.comorbidities')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comorbidities', to='app_cicatrizando.patients')),
            ],
            options={
                'unique_together': {('patient', 'comorbidity')},
            },
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
    ]
