# Generated by Django 5.2 on 2025-05-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cicatrizando", "0002_remove_observation_comorbidities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patients",
            name="comorbidities",
            field=models.ManyToManyField(to="app_cicatrizando.comorbidities"),
        ),
        migrations.DeleteModel(
            name="PatientComorbidities",
        ),
    ]
