# Generated by Django 5.2 on 2025-07-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cicatrizando', '0002_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencaoImediataRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(help_text='ID do paciente associado a este registro de atenção imediata.')),
                ('wound_id', models.IntegerField(help_text='ID da ferida a que este registro de atenção imediata se refere.')),
                ('data_registro', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado.')),
                ('aumento_tamanho', models.BooleanField(default=False, help_text='Indica se a ferida aumentou de tamanho.')),
                ('vermelha_inchada', models.BooleanField(default=False, help_text='Indica se a ferida está mais vermelha ou inchada.')),
                ('saindo_pus_secrecao', models.BooleanField(default=False, help_text='Indica se a ferida está saindo pus ou secreção.')),
                ('doendo_mais', models.BooleanField(default=False, help_text='Indica se a ferida começou a doer mais.')),
                ('pele_quente', models.BooleanField(default=False, help_text='Indica se a pele ao redor da ferida ficou quente.')),
                ('com_febre_mal', models.BooleanField(default=False, help_text='Indica se o paciente está com febre ou se sentindo mal.')),
                ('tempo_mudanca', models.CharField(blank=True, choices=[('HOJE', 'Hoje'), ('ONTEM', 'Ontem'), ('2-3_DIAS', 'Há 2-3 dias'), ('MAIS_3_DIAS', 'Mais de 3 dias')], help_text='Há quanto tempo a mudança na ferida foi notada (se aplicável).', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Atenção Imediata',
                'verbose_name_plural': 'Registros de Atenção Imediata',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='TextoRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(help_text='ID do paciente associado a este texto.')),
                ('conteudo', models.TextField(max_length=2000)),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Texto Recebido',
                'verbose_name_plural': 'Textos Recebidos',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='tissue_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='w_i_fi',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='wound_size_cm2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingrecordimage',
            name='tissue_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackingrecordimage',
            name='w_i_fi',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingrecordimage',
            name='wound_size_cm2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woundimage',
            name='tissue_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='woundimage',
            name='w_i_fi',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woundimage',
            name='wound_size_cm2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
