# Generated by Django 5.2 on 2025-05-16 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cicatrizando", "0003_patients_comorbidities_delete_patientcomorbidities"),
    ]

    operations = [
        migrations.RenameField(
            model_name="specialists",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="wound",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="specialists",
            name="created",
        ),
        migrations.RemoveField(
            model_name="wound",
            name="created",
        ),
        migrations.AddField(
            model_name="images",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="images",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="specialists",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trackingrecords",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trackingrecords",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="wound",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patients",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
