# Generated by Django 6.0.2 on 2026-05-27 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cicatrizando', '0003_patient_alcohol_consumption_patient_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='alcohol_consumption',
            field=models.CharField(blank=True, choices=[('NONE', 'Não bebe'), ('EX', 'Ex-etilista'), ('LT21_M', 'Menos de 21 doses por semana (H)'), ('GT21_M', 'Mais de 21 doses por semana (H)'), ('LT13_M', 'Menos de 13 latas por semana (H)'), ('GT13_M', 'Mais de 13 latas por semana (H)'), ('LT14_F', 'Menos de 14 doses por semana (M)'), ('GT14_F', 'Mais de 14 doses por semana (M)'), ('LT9_F', 'Menos de 9 latas por semana (M)'), ('GT9_F', 'Mais de 9 latas por semana (M)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('NEVER', 'Nunca fumou'), ('LT10', 'Menos de 10 cigarros por dia'), ('GT10', 'Mais de 10 cigarros por dia'), ('EX', 'Ex-tabagista')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)]),
        ),
    ]
