# Generated by Django 6.0.2 on 2026-05-29 09:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cicatrizando', '0004_alter_patient_alcohol_consumption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiology', models.CharField(choices=[('Úlcera do pé diabético', 'Úlcera do pé diabético'), ('Lesão por pressão', 'Lesão por pressão'), ('Úlcera venosa', 'Úlcera venosa'), ('Úlcera arterial', 'Úlcera arterial'), ('Ferida por trauma', 'Ferida por trauma'), ('Ferida cirúrgica', 'Ferida cirúrgica'), ('Queimadura', 'Queimadura'), ('Skin tear', 'Skin tear'), ('Fístula', 'Fístula'), ('Ferida neoplásica', 'Ferida neoplásica'), ('Flebite', 'Flebite')], max_length=50)),
                ('location', models.CharField(choices=[('Anterior do joelho', 'Anterior do joelho'), ('Posterior do joelho', 'Posterior do joelho'), ('Abaixo do joelho, região posterior', 'Abaixo do joelho, região posterior'), ('Abaixo do joelho, região anterior', 'Abaixo do joelho, região anterior'), ('Acima do maleolo medial', 'Acima do maleolo medial'), ('Abaixo do maleolo medial', 'Abaixo do maleolo medial'), ('Acima do maleolo lateral', 'Acima do maleolo lateral'), ('Abaixo do maleolo lateral', 'Abaixo do maleolo lateral'), ('Região calcaneana', 'Região calcaneana'), ('Dorso do pé', 'Dorso do pé'), ('Planta do pé', 'Planta do pé'), ('Halux', 'Halux'), ('2ª Pododáctilo', '2ª Pododáctilo'), ('3ª Pododáctilo', '3ª Pododáctilo'), ('4ª Pododáctilo', '4ª Pododáctilo'), ('5ª Pododáctilo', '5ª Pododáctilo')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_healed', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wounds', to='app_cicatrizando.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pain_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('exudate_amount', models.CharField(choices=[('Nenhum', 'Nenhum'), ('Pouco', 'Pouco'), ('Médio', 'Médio'), ('Muito', 'Muito')], max_length=20)),
                ('exudate_type', models.CharField(choices=[('Seroso', 'Seroso'), ('Purulento', 'Purulento'), ('Sanguinolento', 'Sanguinolento'), ('Serosanguinolento', 'Serosanguinolento'), ('Ausente', 'Ausente')], max_length=20)),
                ('tissue_type', models.CharField(choices=[('Cicatrizado', 'Cicatrizado'), ('Epitelização', 'Epitelização'), ('Granulação', 'Granulação'), ('Desvitalizado', 'Desvitalizado'), ('Necrótico', 'Necrótico')], max_length=20)),
                ('dressing_changes', models.IntegerField()),
                ('periwound_skin', models.CharField(choices=[('Inchaço/Edema', 'Inchaço/Edema'), ('Eritema menor que 2 cm', 'Eritema menor que 2 cm'), ('Eritema maior que 2 cm', 'Eritema maior que 2 cm')], max_length=50)),
                ('wound_edge', models.CharField(choices=[('Indefinidas, não visíveis claramente', 'Indefinidas, não visíveis claramente'), ('Definidas, contorno claramente visível, aderidas, niveladas com a base da ferida', 'Definidas, contorno claramente visível, aderidas, niveladas com a base da ferida'), ('Bem definidas, não aderidas à base da ferida', 'Bem definidas, não aderidas à base da ferida'), ('Bem definidas, não aderidas à base, enrolada, espessada', 'Bem definidas, não aderidas à base, enrolada, espessada'), ('Bem definidas, fibróticas, com crostas e/ou hiperqueratose.', 'Bem definidas, fibróticas, com crostas e/ou hiperqueratose.')], max_length=255)),
                ('fever_24h', models.BooleanField(default=False)),
                ('extra_notes', models.TextField(blank=True, null=True)),
                ('patient_guidelines', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cicatrizando.woundsuser')),
                ('wound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='app_cicatrizando.wound')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
