# Generated by Django 6.0.2 on 2026-06-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cicatrizando', '0005_wound_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wounds/observations/'),
        ),
    ]
