# Generated by Django 6.0.2 on 2026-06-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cicatrizando', '0006_observation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='observations/'),
        ),
    ]
