services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-impexp:/home
    restart: on-failure:5
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "$$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    image: wounds-server:v0.1
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_URL: postgresql://postgres:postgres@db:5432/postgres

volumes:
  postgres-data:
  postgres-impexp:
  midia:
    driver: local
    driver_opts:
      type: none
      device: ./midia
      o: bind