FROM python

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /code/

ENTRYPOINT ["bash", "/code/docker/entrypoint.sh"]
