FROM python:3.12-slim

WORKDIR /code

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && pip install gunicorn

COPY . .

EXPOSE 8000

ENTRYPOINT ["bash", "/code/docker/entrypoint-prod.sh"]